POST http://localhost:5000/user/verify
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDFlOGZlNWZiNmM3YTExODRkOWM3ZCIsInVzZXJJZCI6InByaXNtYSIsIm5hbWUiOm51bGwsImlhdCI6MTY2MTEwMTc1NCwiZXhwIjoxNjYxMTAyMzU0fQ.fN0wUoS_mRjk3lK444hESgdNzC8oLh81veftuohh

###

POST http://localhost:5000/user/login
Content-Type: application/json

{
  "userId" : "prisma",
  "password" : "prismaTest"
}

###

POST http://localhost:5000/user/logout
Content-Type: application/json

{
  "id" : "6301e8fe5fb6c7a1184d9c7d"
}